const UserActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',

    CHECK_USER_SESSION: 'CHECK_USER_SESSION',

    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',

    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
}

export default UserActionTypes;